# Generated by Django 5.2.8 on 2025-12-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_contribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingplan',
            old_name='name',
            new_name='name_of_plan',
        ),
    ]
