# Generated by Django 5.2.8 on 2025-12-18 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_rename_name_savingplan_name_of_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saving_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='savings.savingplan')),
            ],
        ),
    ]
