# Generated by Django 5.2.8 on 2025-12-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_withdrawal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingplan',
            old_name='name_of_plan',
            new_name='name',
        ),
    ]
